@baseUrl=http://localhost:3000/api
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEwLCJpYXQiOjE2NDgzOTU3MDAsImV4cCI6MTY1MDk4NzcwMH0.PeyCmrQtcnyEWlB6QirUrADZ_TUUgvRMxZtMStDHv3w
@productionToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjksImlhdCI6MTY0ODE0MDc5OSwiZXhwIjoxNjUwNzMyNzk5fQ.cS3yD6WjYzjjlPx8C2yORRqC1z-RYmGbP-9nt_VIAZ0
@devToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEwLCJpYXQiOjE2NDgzOTU3MDAsImV4cCI6MTY1MDk4NzcwMH0.PeyCmrQtcnyEWlB6QirUrADZ_TUUgvRMxZtMStDHv3w
###
POST {{baseUrl}}/admin/user/1/potential-issue/history
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "userId": 1,
  "startWeek": 2,
  "startYear": 2021,
  "endWeek": 4,
  "endYear": 2023
}

