export const dateRange = {
    DAY_OF_YEAR: 363,
    DAY_OF_WEEK: 7,
    MILLISECONDS_IN_DAY: 86400000,
    TIME_ZONE_OFFSET: 420,
    DURATION_BETWEEN_START_AND_END: 6,
    UTC: 7,
};
export const MOMENT_DAY_OF_WEEK = 6;
